export const SIDEBAR_OPEN = 'SIDEBAR_OPEN';
export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE';

export const GET_LOGIN_BEGIN = 'GET_LOGIN_BEGIN';
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS';
export const GET_LOGIN_ERROR = 'GET_LOGIN_ERROR';

export const GET_EVENTS_BEGIN = 'GET_EVENTS_BEGIN';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_ERROR = 'GET_EVENTS_ERROR';
export const GET_SINGLE_EVENT_SUCCESS = 'GET_SINGLE_EVENT_SUCCESS';

export const GET_POST_DATA_BEGIN = 'GET_POST_DATA_BEGIN';
export const GET_POST_DATA_SUCCESS = 'GET_POST_DATA_SUCCESS';
export const GET_POST_DATA_ERROR = 'GET_POST_DATA_ERROR';

export const ADDRESS_LIST_CHANGE = 'ADDRESS_LIST_CHANGE';

export const EVENT_DETAIL_CHANGE = 'EVENT_DETAIL_CHANGE';
export const EVENT_OPTION_ADD = 'EVENT_OPTION_ADD';
export const EVENT_OPTION_DELETE = 'EVENT_OPTION_DELETE';
export const EVENT_RESET = 'EVENT_RESET';
export const EVENT_TIME_CHANGE = 'EVENT_TIME_CHANGE';

export const POST_NEW_EVENT_BEGIN = 'POST_NEW_EVENT_BEGIN';
export const POST_NEW_EVENT_SUCCESS = 'POST_NEW_EVENT_SUCCESS';
export const POST_NEW_EVENT_ERROR = 'POST_NEW_EVENT_ERROR';
